config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :preferences, only: [:new, :create]
  resources :resorts, only: [:index, :show] do
    resources :activities, only: [:index]
  end
end

app/models/resort.rb
class Resort < ApplicationRecord
    has_many :activities
    geocoded_by :resort_address
    after_validation :geocode, if: :will_save_change_to_resort_address?
    has_many_attached :landscapes

    has_one :preference, as: :matchable

    def distance(preference)
      rad_per_deg = Math::PI/180  # PI / 180
      rkm = 6371                  # Earth radius in kilometers
      rm = rkm * 1000             # Radius in meters
      loc2 = [latitude, longitude]
      loc1 = [preference.latitude, preference.longitude]
      dlat_rad = (loc2[0]-loc1[0]) * rad_per_deg  # Delta, converted to rad
      dlon_rad = (loc2[1]-loc1[1]) * rad_per_deg

      lat1_rad, lon1_rad = loc1.map {|i| i * rad_per_deg }
      lat2_rad, lon2_rad = loc2.map {|i| i * rad_per_deg }

      a = Math.sin(dlat_rad/2)**2 + Math.cos(lat1_rad) * Math.cos(lat2_rad) * Math.sin(dlon_rad/2)**2
      c = 2 * Math::atan2(Math::sqrt(a), Math::sqrt(1-a))

      (rm * c / 1000).round# Delta in meters
    end
end

app/controllers/resorts_controller.rb
class ResortsController < ApplicationController
    skip_before_action :authenticate_user!, only: [ :index, :show ]
    before_action :set_resort, only: [ :show ]

    def index
        if params[:query].present?
          sql_query = "resort_name @@ :query OR resort_description @@ :query"
          @resorts = Resort.where(sql_query, query: "%#{params[:query]}%")
                           .map { |resort| [resort, nil]}

        elsif current_user

          # Ici on va trier les resorts en fonction des préférences

          # On récupère la préférence du user (preference)
          @resorts = current_user.top_resorts

        else
          user = User.find_by_id(session[:user_id])
          @resorts = user.top_resorts # [[#<Resort....>, 67], [......]
        end
    end

    def show
      @resort = Resort.new
      @resort = Resort.find(params[:id])
      @activity = Activity.new

      @markers = [{
        lat: @resort.latitude,
        lng: @resort.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { resort: @resort })
      }]

      @loc = current_user and current_user.preference ? [
        { lat: current_user.preference.latitude, lng: current_user.preference.longitude },
        { lat: @resort.latitude, lng: @resort.longitude }
      ] : nil

    end

    def set_resort
        @resort = Resort.find(params[:id])
    end

    def resort_params
        params.require(:resort).permit(:resort_name, :resort_addres, :resort_description, :visitor_name, :roommate, :budget,
        :day_activities, :biological_clock, :accommodation, :spot, :night_activities, :expectations, :geocation, :kilometers, :photo_asset)
    end
end

app/views/resorts/_all_resorts.html.erb
<% if params[:query].present? %>

<div class="banner-index-all d-flex justify-content-center  flex-column">

  <div class="container-title-index-all ">
    <div class="row">
      <div class="index-infos-all">
        <h1 class="title-index-all">Vos stations françaises</h1>
        <p class="all-resorts-p">Retrouve toutes les stations disponibles!</br>
          Parcours skifind afin de trouver <strong>TA</strong> station préférée. </br>
          Mais si tu veux allier envies et ski, n'hésite pas à parler avec Georges!</p>
      </div>
    </div>
  </div>

    <div class="container d-flex justify-content-center">
      <div class="row">
        <div>
          <% @resorts.each do |resort|  %>
            <%= link_to resort_path(resort), class: 'link-without-style' do %>
              <div class="card-product">
                <%= image_tag resort[0].photo_asset, alt: "Tignes", width: 200, class: "img-resort" %>
                <div class="card-product-infos">
                  <%= resort[1] %>
                    <p class="localisation-all"><i class="fas fa-map-marked-alt icon-color"></i> <%= resort[0].resort_address %></p>
                    <div class="info-resort name mb-5">
                      <h3 class="localisation-mountains"> <%= resort[0].mountains %> </h3>
                      <h4 class="titre_h4_go"><%= resort[0].resort_name %></h4>
                    </div>
                    <div class="info-picto-description">
                      <i class="fas fa-skiing pictogramme-color"></i><span> <%=  resort[0].slopes_title%></span>
                      <i class="fas fa-mountain pictogramme-color"></i><span><%= resort[0].altitude %></span>
                      <i class="fas fa-bacon pictogramme-color"></i><span><%= resort[0].kids_garden %></span>
                      <i class="fas fa-snowboarding pictogramme-color"></i><span><%= resort[0].snowpark %></span>
                    </div>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/resorts/_chart.html.erb
<div class="d-flex" style="position: relative;">
    <div class="text-center w-100"></div>
    <div style="position: absolute; right: 22px; top: 32px; font-weight: bold;"><%= resort[1] %> %</div>
    <canvas id="myChart<%= resort[0].id %>" width="200" height="200" ></canvas>

</div>

app/views/resorts/_georges_resorts.html.erb
  <% if !params[:query].present? %>
   <div class="banner-george d-flex justify-content-center align-items-center flex-column">
    <div class="container-title-index ">
      <div class="row">
        <div class="index-infos">
          <h2 class="title-index" style= "text-align: center; font-size: 36px;">Voici la meilleure sélection que je t'ai trouvé :</h2>
        </div>
      </div>
    </div>
    <div class="container d-flex justify-content-center">
      <div class="row">
        <div id="resorts" data-resorts="<%= @resorts.map { |resort| [resort[0].to_json, resort[1]]} %>"></div>
        <% @resorts.each do |resort| %>
          <div class="col-12 col-lg-4">
            <div class="card">
              <div class="card-choose" >
                <%= link_to resort_path(resort), class: 'link-without-style' do %>
                  <%= image_tag resort[0].photo_asset, alt: "Tignes", class: "photo" %>
                  <%= image_tag resort[0].resort_name.downcase + '-logo.png', class: 'logo' %>
                  <h5 class="titre-station-pref"><%= resort[0].resort_name %></h5>
                    <div id="data-resort"></div>
                    <%= render 'chart', resort: resort %>
                  <% resort[0].preference.attributes.except("id", "latitude", "longitude", "visitor_name", "matchable_type", "matchable_id", "created_at", "updated_at", "spot", "biological_clock", "kilometers", "geocation").each do |k,v| %>
                    <p class="d-flex justify-content-between" style = "font-weight: bold; color: #02245C; font-size: 15px; text-transform: capitalize; margin-bottom: 13px; margin-top: 15px;"><%= v %><i class="fas fa-check green-tick"></i></p>
                  <% end %>
                <% end %>
              </div>
            </div>
            <p class="localisation"><i class="fas fa-map-marked-alt icon-color"></i> <%= resort[0].mountains %></p>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/resorts/_info_window.html.erb
<div class="itinerary">
  <% if current_user and current_user.preference and current_user.preference.latitude %>
    <h6 class="text-window">Vous êtes à </h6>
    <h2 class="distance"> <%= @resort.distance(current_user.preference) %> km</h2>
    <h6 class="text-window"> de votre station idéale : </h6>
    <h6 class="resort-name-window"> <%= resort.resort_name %> </h6>
  <% end %>
</div>

app/views/resorts/index.html.erb
<%= render 'all_resorts'  %>
<%= render 'georges_resorts'  %>

app/views/resorts/show.html.erb
<!-----------------------carousel ------------------------->
<div id="resort-show" data-loc="<%= @loc.to_json %>"></div>
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
     <div class="carousel-inner ">
    <div class="carousel-caption ">
      <h1 class="resort-title mt-3"><%= @resort.resort_name %></h1>
      <div class="massif-position">
        <p class="massif-show" style="font-size: 32px;"> <%= @resort.mountains %> </p>
        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-chevron-double-down" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M1.646 6.646a.5.5 0 0 1 .708 0L8 12.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/>
        <path fill-rule="evenodd" d="M1.646 2.646a.5.5 0 0 1 .708 0L8 8.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/>
        </svg>
      </div>
    </div>
    <% @resort.landscapes.each_with_index do |photo, index| %>
       <div class="carousel-item <%= 'active' if index == 0 %>">
         <div class="photo-caroussel" style="background-image: url('<%= cl_image_path photo.key %>');"></div>
       </div>
    <% end %>
    <!-- <div class="resort-title mt-3">
          <h3><%= @resort.resort_name %></h3>
          </div> -->
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

  <!-----------------------card station ------------------------->
<div class="container-show">
  <div class="back-cta">
    <%= link_to "Mes résultats", resorts_path, class: "buton-primary-show link-without-style" %>

  </div>

  <!-----------------------card station ------------------------->
  <div class="card-station">
    <div class="card-station-info">

      <div class="slopes-pictogramme">

        <div class="total-slopes">

            <i class="fas fa-skiing fa-10x pictogramme-color " style="font-size: 34px;"></i><span class="size-number"><%= @resort.slopes_title %> </span><span class="span-picto"> pistes </span>

        </div>

        <div class="pair-slopes">
          <div class="green-slopes">
            <%= @resort.slopes_green %>
          </div>

          <div class="blue-slopes">
            <%= @resort.slopes_blue %>
          </div>
        </div>

        <div class="pair-slopes">
          <div class="red-slopes">
            <%= @resort.slopes_red %>
          </div>
          <div class="black-slopes">
            <%= @resort.slopes_black %>
          </div>
        </div>

      </div>

      <div class="infos-pictogramme">
          <div class="altitude">
            <i class="fas fa-mountain pictogramme-color" style="font-size: 34px;"></i><span class="size-number"><%= @resort.altitude.split[0] %></span> <span class="span-picto"> mètres</span>
          </div>
          <div class="snowpark">
             <i class="fas fa-snowboarding pictogramme-color" style="font-size: 34px;"></i><span class="size-number"><%= @resort.snowpark.split[0] %></span> <span class="span-picto"> snowparks</span>
          </div>
          <div class="kilometers-slopes">
            <i class="fas fa-bacon pictogramme-color" style="font-size: 34px;"></i><span class="size-number"><%= @resort.kids_garden.split[0] %></span><span class="span-picto"> km de pistes</span>
          </div>
      </div>

    </div>
    <div>
       <span class="localisation-show"> <i class="fas fa-map-marked-alt icon-color"></i> <%= @resort.resort_address %></span>
    </div>
        <%= render 'shared/map' %>


    <div class="card-station-cta">
      <div class="d-flex justify-content-center align-items-center pb-5">
        <div class="button-website">
          <%= link_to "Réserve ton séjour", @resort.resort_website, class: "buton-primary-show link-without-style", target: "_blank"  %>
        </div>
      </div>
      <div></div>
    </div>

  </div>

<div class="description">

  <div class="title-description">

    <h2 class="title-description-size" style="font-size: 42px;"><span class="word"> Pourquoi <%= @resort.resort_name %> ? </span></h2>

  </div>

  <div class="text-infos" style="font-size: 25px;">
    <%= @resort.resort_description %>
  </div>
</div>
</div>

   <!-----------------------card activity ------------------------->

    <div class="container mt-5">
      <div class="row">
        <% @resort.activities.each do |activity|  %>
          <div class="col-sm-12 col-md-6 col-lg-4">
            <div class="card-activity">
              <div class="inner">
                <%= cl_image_tag activity.photo.key, class: "card-img-top" %>
              </div>
              <div class="card-body d-flex flex-column justify-content-between">
                <h4 class="card-title" style="text-align: center;"><span class="word"> <%= activity.activity_name %> </span></h5>
                <p class="card-text" style="font-size: 20px">
                  <%= activity.activity_description %>
                </p>
                <div class="d-flex justify-content-end flex-column" style="height: 100%;">
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>